language: node_js
node_js:
- '10.10.0'
dist: trusty
sudo: true
cache:
  directories:
    - node_modules
addons:
  chrome: stable
before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - google-chrome-stable --headless --no-sandbox --disable-gpu --remote-debugging-port=9876 http://localhost &
install:
  - npm install
  # - npm install -g karma-cli
  # - npm install -g bower
env:
  global:
    - B_NAME1=develop
    - B_NAME2=master
    - B_NAME3=test
    #- GOOGLE_CHROME_BINARY=/usr/bin/google-chrome-beta
    #- if [ "$TRAVIS_BRANCH"=master]; then B_NAME=master; elif [ "$TRAVIS_BRANCH"=develop] then B_NAME=develop; else B_NAME=test; fi
    #- if [ "$TRAVIS_BRANCH"=develop]; then B_NAME=develop; fi
    #- if [ "$TRAVIS_BRANCH"=test]; then B_NAME=test; fi
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - export CHROME_BIN=chromium-browser
    # Print build info that binary is compiled with.
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - echo $TRAVIS_BRANCH
    - echo $TRAVIS_BUILD_NUMBER
    - echo $B_NAME
script:
  - npm run build
  # - npm run test
  # - npm run lint

 # - xvfb-run npm run e2e
before_deploy:
    - if [ "$TRAVIS_BRANCH"=master ]; then B_NAME=master; fi
    #- if [ "$TRAVIS_BRANCH"=develop ]; then B_NAME=develop; fi
    #- if [ "$TRAVIS_BRANCH"=test ]; then B_NAME=test; fi
    #- echo $B_NAME
    - if [ "$TRAVIS_BRANCH" = master ]; then echo "master"; mv index_uat.html index.html; fi
    - if [ "$TRAVIS_BRANCH" = test ]; then echo "test"; mv index_staging.html index.html; fi
deploy:
  - provider: cloudfoundry
    edge: false
    username: nmdsdevopsserviceadm@hotmail.com
    password:
      secure: "lExM3YdDZMXTpXu6tjLpZxPbtgPqr0pc+sNPJG/m9RCsOicy0A62EUAn+wtF3XYDjcI63OJHErni/uk9Z0qa5uKE+qES+1OllncN41RynjI8t3T6qNCpTvQbw0LpueedlVImbK4IcCVCiyYzrf14e8EX4tGCOCWybDqeg4cXySTKEQe1ZhGeqzLYMoG7xrNJqavBoaMwFxgSSyDf4gcvvJzgFYSNT0EDMhhv+3rvReCPmYPM34TXkWU49WX6p9ABT8B01Uejp5AMFyKj5KCX6asYSkvaNkR+Z/JkUQ69HenVXsgYeYlJBp3zBNm6n0f6heFJ+QJ3JrP8ErDMzGW5/ZxLq/gqj8SfAmwzKPKzk6pG7mtTdpKXYkpgL6vU2PTX6OSE/FIO6EP6A3IiUDGoBML85rcQUAP59I4lKR+hxgDcMQ15gToun/TJWm/XiM9IMPpKgtuFC04KuYhSHLzVmhFrrgV7W0sk+B3n3iWR11ivu0T9aYKheD3xbm6/JqZgP7vxIZB4iRllPj5Kx/RntePrJQzmvGiDGYalEckhVJ5R4dMEBBUJTkB3gDArgUDfyS4d6fNCYC/8THb6Cj/IWRPuw8di5rAUjI93p7vmmucVtQ0IjLN/vEMdVtyUOmwmpa0sVNtXSnzoEcll5uS3xsa23KUSjR1WNiyRd1i3D0U="
    api: https://api.cloud.service.gov.uk
    organization: dhsc-skills-for-care-nmds-sc-2
    space: sandbox
    manifest: manifest.dev.yml
    on:
        branch: develop
  - provider: cloudfoundry
    edge: false
    username: nmdsdevopsserviceadm@hotmail.com
    password:
      secure: "lExM3YdDZMXTpXu6tjLpZxPbtgPqr0pc+sNPJG/m9RCsOicy0A62EUAn+wtF3XYDjcI63OJHErni/uk9Z0qa5uKE+qES+1OllncN41RynjI8t3T6qNCpTvQbw0LpueedlVImbK4IcCVCiyYzrf14e8EX4tGCOCWybDqeg4cXySTKEQe1ZhGeqzLYMoG7xrNJqavBoaMwFxgSSyDf4gcvvJzgFYSNT0EDMhhv+3rvReCPmYPM34TXkWU49WX6p9ABT8B01Uejp5AMFyKj5KCX6asYSkvaNkR+Z/JkUQ69HenVXsgYeYlJBp3zBNm6n0f6heFJ+QJ3JrP8ErDMzGW5/ZxLq/gqj8SfAmwzKPKzk6pG7mtTdpKXYkpgL6vU2PTX6OSE/FIO6EP6A3IiUDGoBML85rcQUAP59I4lKR+hxgDcMQ15gToun/TJWm/XiM9IMPpKgtuFC04KuYhSHLzVmhFrrgV7W0sk+B3n3iWR11ivu0T9aYKheD3xbm6/JqZgP7vxIZB4iRllPj5Kx/RntePrJQzmvGiDGYalEckhVJ5R4dMEBBUJTkB3gDArgUDfyS4d6fNCYC/8THb6Cj/IWRPuw8di5rAUjI93p7vmmucVtQ0IjLN/vEMdVtyUOmwmpa0sVNtXSnzoEcll5uS3xsa23KUSjR1WNiyRd1i3D0U="
    api: https://api.cloud.service.gov.uk
    organization: dhsc-skills-for-care-nmds-sc-2
    space: sandbox
    manifest: manifest.test.yml
    on:
        branch: test
  - provider: cloudfoundry
    edge: false
    username: nmdsdevopsserviceadm@hotmail.com
    password:
      secure: "lExM3YdDZMXTpXu6tjLpZxPbtgPqr0pc+sNPJG/m9RCsOicy0A62EUAn+wtF3XYDjcI63OJHErni/uk9Z0qa5uKE+qES+1OllncN41RynjI8t3T6qNCpTvQbw0LpueedlVImbK4IcCVCiyYzrf14e8EX4tGCOCWybDqeg4cXySTKEQe1ZhGeqzLYMoG7xrNJqavBoaMwFxgSSyDf4gcvvJzgFYSNT0EDMhhv+3rvReCPmYPM34TXkWU49WX6p9ABT8B01Uejp5AMFyKj5KCX6asYSkvaNkR+Z/JkUQ69HenVXsgYeYlJBp3zBNm6n0f6heFJ+QJ3JrP8ErDMzGW5/ZxLq/gqj8SfAmwzKPKzk6pG7mtTdpKXYkpgL6vU2PTX6OSE/FIO6EP6A3IiUDGoBML85rcQUAP59I4lKR+hxgDcMQ15gToun/TJWm/XiM9IMPpKgtuFC04KuYhSHLzVmhFrrgV7W0sk+B3n3iWR11ivu0T9aYKheD3xbm6/JqZgP7vxIZB4iRllPj5Kx/RntePrJQzmvGiDGYalEckhVJ5R4dMEBBUJTkB3gDArgUDfyS4d6fNCYC/8THb6Cj/IWRPuw8di5rAUjI93p7vmmucVtQ0IjLN/vEMdVtyUOmwmpa0sVNtXSnzoEcll5uS3xsa23KUSjR1WNiyRd1i3D0U="
    api: https://api.cloud.service.gov.uk
    organization: dhsc-skills-for-care-nmds-sc-2
    space: sandbox
    manifest: manifest.featureGDS.yml
    on:
        branch: develop_accessibility_demo
notifications:
    slack: skills-for-care:Co9S4WS4ZitevGOyBrEb6yEL
