version: 0.2

run-as: codebuild-user

env:
  variables:
    NODE_OPTIONS: "--max_old_space_size=8192"
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    run-as: root
    commands:
      - chown -R codebuild-user:codebuild-user "/root/.npm"
  build:
    commands:
      - cd frontend && npm ci
      - npm run build:test
      - cd ../backend && npm ci