version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 636146736465.dkr.ecr.eu-west-1.amazonaws.com
      - export manifest=$(aws ecr batch-get-image --repository-name sfc-backend-build-images --image-ids imageTag=latest --output text --query 'images[].imageManifest')

  build:
    commands:
      - COMMIT_HASH=$(aws ecr describe-images --repository-name sfc-backend-build-images --image-ids imageTag=latest --output text | awk '{print $2}' | tail -n1)
      - echo Retagging the latest ecr image...
      - aws ecr batch-delete-image --repository-name sfc-backend-build-images --image-ids imageTag=staging
      - aws ecr put-image --repository-name sfc-backend-build-images --image-tag staging --image-manifest "$manifest"
      - aws app-runner deploy --instance AWS_STAGING_APP_RUNNER_ARN # THIS IS PYUDOCODE
      - aws apprunner start-deployment --service-arn arn:aws:apprunner:eu-west-1:101248264786:service/sfc-app-runner-staging/9e440da7842b4153bd211b2ca2645353
      - echo Copy s3 bucket from bnd to staging...
      - aws s3 cp --recursive s3://sfc-frontend-build-artifacts/$COMMIT_HASH s3://sfc-frontend-staging/

