version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  build:
    commands:
      - cd frontend && npm ci
      - npm run build
      - npm install -g @lhci/cli@0.12.x
      - lhci autorun