version: 0.2

env:
  variables:
      JUNIT_REPORT_PATH: ./junit/
      JUNIT_REPORT_NAME: test-results.xml
phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - npm run test-headless