version: 0.2

env:
  variables:
      MOCHA_FILE: ./junit/test-results.xml
      NODE_ENV: example

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - apt-get update
  build:
    commands:
      - cd backend
      - npm run server:lambda:cover:unit:ci; EXITCODE=$?