aws:
    region: eu-west-1
    secrets:
        use: true
        wallet: benchmarks/api
    kinesis:
      enabled: true
      establishments: establishments.dev
      workers: workers.dev
      users: users.dev
    sns:
      enabled: true
      registrations: arn:aws:sns:eu-west-1:364648107127:registrations-dev
      feedback: 	arn:aws:sns:eu-west-1:364648107127:feedback-dev

db:
    pool:
        min: 10
        max: 10
    ssl: true
    client_ssl:
        status: false
        usingFiles: false

slack:
    level : 3     # enables Slack notifications

jwt:
    iss: 'sfcbenchmarks.cloudapps.digital'
    ttl:
        login: 30

bulkupload:
    region: eu-west-2
    bucketname: sfc-bulkupload-dev
    validation:
        timeout: 300
        storeIntermediaries: true
    completion:
        timeout: 180

public:
    download:
        baseurl: https://sfc-public-dev.s3.eu-west-2.amazonaws.com/public/download

# no notify definition - not used in development
