aws:
    region: eu-west-1
    secrets:
        use: false
        wallet: dev/api
    sqsqueue: http://0.0.0.0:9324/updates

db:
    ssl: false
    username: sfcadmin
    client_ssl:
        status: false
        usingFiles: false
log:
    sequelize: false
