aws:
    region: eu-west-1
    secrets:
        use: false
        wallet: dev/api

db:
    ssl: false
    username: sfcadmin
    client_ssl:
        status: false
        usingFiles: false
log:
    sequelize: false
